MODEL:
  ENCODER:
    N_LAYERS: 6
    N_HEADS: 8
    D_MODEL: 512
    D_FFN: 2048
    DROPOUT: 0.1
    EPS: 0.1

  DECODER:
    N_LAYERS: 6
    N_HEADS: 8
    D_MODEL: 512
    D_FFN: 2048
    DROPOUT: 0.1
    EPS: 0.1

DATA:
  MAX_LEN: 160
  BATCH_SIZE: 2048 # number of tokens in a batch

OPTIM:
  INIT_LR: 0.2
  N_WARMUP_STEPS: 3000

TRAINER:
  N_EPOCHS: 2

